// Generated by CoffeeScript 1.6.3
(function() {
  var Fog, Responsive;

  Fog = (function() {
    function Fog() {
      jQuery(".all-fog-slider").height(jQuery(window).height() + "px");
      jQuery("#fog-slider").height(jQuery(window).height() + "px");
      this.init();
      return;
    }

    Fog.prototype.init = function() {
      jQuery("#sticky-menu").waypoint('sticky');
      this.initHoverDir();
      this.initLavaLamp();
      this.initBlocks();
      this.initMap();
      this.styleCollapse();
      this.ajaxBinds();
      this.quoteSlider();
      this.twitterSlider();
      this.slideshowSlider();
      this.testimonialsSlider();
      this.initScrollTo();
      this.changeContent();
      this.initColorbox();
    };

    Fog.prototype.initLavaLamp = function() {
      return jQuery(".main-menu .l-inline").lavaLamp();
    };

    Fog.prototype.initHoverDir = function() {
      return jQuery('.inline-menu-body > li').each(function() {
        return jQuery(this).hoverdir();
      });
    };

    Fog.prototype.initRevolutionSlider = function() {
      jQuery("#fog-slider").revolution({
        delay: 9000,
        startheight: 895,
        startwidth: 320,
        thumbWidth: 100,
        thumbHeight: 50,
        thumbAmount: 5,
        onHoverStop: "off",
        hideThumbs: 200,
        navigationType: "bullet",
        navigationStyle: "round",
        navigationArrows: "none",
        touchenabled: "on",
        navOffsetHorizontal: 0,
        navOffsetVertical: 20,
        fullWidth: "on",
        fullScreen: "on",
        shadow: 0
      });
    };

    Fog.prototype.changeContent = function() {
      var self;
      self = this;
      return jQuery(".filters .inline-menu a").on("click", function() {
        var activeChild, childrens, container, el, index;
        el = jQuery(this);
        index = el.parent().index();
        container = el.closest(".filters");
        childrens = container.find(".filter-content");
        activeChild = childrens.eq(index);
        el.parent().siblings().find("a").removeClass("is-active");
        el.addClass("is-active");
        if (activeChild.hasClass("hidden")) {
          childrens.fadeOut("fast", function() {
            return jQuery(this).addClass("hidden");
          });
          activeChild.css({
            opacity: 0
          }).removeClass("hidden");
          new Animo({
            el: activeChild,
            duration: 500,
            delay: 100,
            template: {
              opacity: [0, 1]
            }
          });
        }
        return false;
      });
    };

    Fog.prototype.initBlocks = function() {
      this.animateIntroduction();
      this.animatePortfolio();
      this.animateQuotes();
      this.animateServices();
      this.animateAbout();
      this.animateTeam();
      this.animateBlog();
      this.animateTouch();
      this.animateContact();
      return this.animateShortcodes.init();
    };

    Fog.prototype.animateIntroduction = function() {
      var _this = this;
      return jQuery("#intro").waypoint(function() {
        return _this.initIntroduction();
      }, {
        triggerOnce: true,
        offset: 400
      });
    };

    Fog.prototype.animatePortfolio = function() {
      var _this = this;
      return jQuery("#intro").waypoint(function() {
        return new Animo({
          el: jQuery("#portfolio .fog-title"),
          duration: 600,
          delay: 1000,
          template: {
            scale: [2, 1],
            opacity: [0, 1]
          }
        }, {
          el: jQuery("#portfolio .inline-menu"),
          duration: 600,
          delay: 1500,
          template: {
            opacity: [0, 1],
            "margin-left": [-200, 0, "px"]
          }
        }, {
          el: jQuery("#portfolio .inline-menu-body li"),
          duration: 500,
          delay: 2000,
          gap: -85,
          easing: "easeOutBack",
          template: {
            opacity: [0, 1],
            scale: [0, 1],
            rotate: [-90, 0, "deg"]
          }
        });
      }, {
        triggerOnce: true,
        offset: 300
      });
    };

    Fog.prototype.animateQuotes = function() {
      var _this = this;
      return jQuery("#quotes").waypoint(function() {
        return new Animo({
          el: jQuery("#quotes .single-quote h4, #quotes .single-quote p, #quotes .single-quote small"),
          duration: 400,
          delay: 0,
          gap: -15,
          easing: "easeOutBack",
          template: {
            opacity: [0, 1],
            translateY: [50, 0, "px"]
          }
        });
      }, {
        triggerOnce: true,
        offset: 600
      });
    };

    Fog.prototype.animateServices = function() {
      var _this = this;
      return jQuery("#services").waypoint(function() {
        return new Animo({
          el: jQuery("#services .fog-title"),
          duration: 600,
          template: {
            scale: [2, 1],
            opacity: [0, 1]
          }
        }, {
          el: jQuery("#services .inline-menu"),
          duration: 600,
          delay: 500,
          template: {
            opacity: [0, 1],
            "margin-left": [-200, 0, "px"]
          }
        }, {
          el: jQuery("#services .inline-menu-body li"),
          duration: 500,
          delay: 1000,
          gap: -65,
          easing: "easeOutBack",
          template: {
            opacity: [0, 1],
            scale: [1.5, 1],
            rotateX: [240, 0, "deg"]
          }
        });
      }, {
        triggerOnce: true,
        offset: 400
      });
    };

    Fog.prototype.animateAbout = function() {
      var _this = this;
      return jQuery("#about").waypoint(function() {
        _this.fogProgress();
        return new Animo({
          el: jQuery("#about h3.fog-title"),
          duration: 600,
          template: {
            scale: [2, 1],
            opacity: [0, 1]
          }
        }, {
          el: jQuery("#about .fog-progress"),
          easing: "easeOutElastic",
          delay: 600,
          gap: -80,
          template: {
            opacity: [0, 1],
            translateY: [-100, 0, "%"]
          }
        }, {
          el: jQuery("#about .about-info"),
          easing: "easeOutElastic",
          delay: 600,
          gap: -80,
          template: {
            opacity: [0, 1],
            translateY: [100, 0, "%"]
          }
        }, {
          el: jQuery("#about .bottom-about"),
          delay: 1200,
          duration: 600,
          template: {
            opacity: [0, 1],
            translateX: [-50, 0, "px"]
          }
        });
      }, {
        triggerOnce: true,
        offset: 400
      });
    };

    Fog.prototype.animateTeam = function() {
      var _this = this;
      return jQuery("#team").waypoint(function() {
        return new Animo({
          el: jQuery("#team .fog-title"),
          duration: 600,
          template: {
            scale: [2, 1],
            opacity: [0, 1]
          }
        }, {
          el: jQuery("#team .inline-menu"),
          duration: 600,
          delay: 500,
          template: {
            opacity: [0, 1],
            "margin-left": [-200, 0, "px"]
          }
        }, {
          el: jQuery("#team .inline-menu-body li"),
          duration: 500,
          delay: 1000,
          gap: -65,
          easing: "easeOutBack",
          template: {
            opacity: [0, 1],
            scale: [1.5, 1],
            rotateX: [240, 0, "deg"]
          }
        });
      }, {
        triggerOnce: true,
        offset: 400
      });
    };

    Fog.prototype.animateBlog = function() {
      var _this = this;
      return jQuery("#blog").waypoint(function() {
        return new Animo({
          el: jQuery("#blog h3.fog-title"),
          duration: 600,
          template: {
            scale: [2, 1],
            opacity: [0, 1]
          }
        }, {
          el: jQuery("#blog #blog-inner article"),
          delay: 500,
          duration: 400,
          gap: -50,
          template: {
            opacity: [0, 1],
            translateX: [-50, 0, "px"]
          }
        }, {
          el: jQuery("#blog .fog-pagination"),
          delay: 1250,
          duration: 400,
          template: {
            opacity: [0, 1],
            translateX: [-50, 0, "px"]
          }
        });
      }, {
        triggerOnce: true,
        offset: 400
      });
    };

    Fog.prototype.animateTouch = function() {
      var _this = this;
      return jQuery("#contact-touch").waypoint(function() {
        return new Animo({
          el: jQuery("#contact-touch h3.fog-title"),
          duration: 600,
          template: {
            scale: [2, 1],
            opacity: [0, 1]
          }
        }, {
          el: jQuery("#contact-touch p"),
          gap: -75,
          delay: 500,
          duration: 200,
          template: {
            translateX: [-10, 0, "px"],
            opacity: [0, 1]
          }
        }, {
          el: jQuery("#contact-touch .bottom-contact"),
          delay: 800,
          duration: 200,
          template: {
            translateX: [10, 0, "px"],
            opacity: [0, 1]
          }
        });
      }, {
        triggerOnce: true,
        offset: 400
      });
    };

    Fog.prototype.animateContact = function() {
      var _this = this;
      return jQuery("#contact-form").waypoint(function() {
        return new Animo({
          el: jQuery("#contact-form h3.fog-title"),
          duration: 600,
          template: {
            scale: [2, 1],
            opacity: [0, 1]
          }
        }, {
          el: jQuery("#contact-form form .fog"),
          gap: -75,
          delay: 500,
          duration: 200,
          template: {
            translateX: [-10, 0, "px"],
            opacity: [0, 1]
          }
        });
      }, {
        triggerOnce: true,
        offset: 400
      });
    };

    Fog.prototype.animateShortcodes = {
      init: function() {
        this.animateTypo();
        this.animateTabs();
        this.animateAccordions();
        this.animateWell();
        this.animateDropProgress();
        this.animateTypeList();
        this.animateAjaxPortfolio();
        this.animateButtons();
        this.animateMessages();
        this.animateContentBox();
        this.animateTestimonials();
        this.animateScForm();
      },
      animateTypo: function() {
        var _this = this;
        return jQuery("#fog-typograpy").waypoint(function() {
          return new Animo({
            el: jQuery("#fog-typograpy h1.fog-title"),
            duration: 600,
            template: {
              scale: [2, 1],
              opacity: [0, 1]
            }
          }, {
            el: jQuery("#fog-typograpy .row"),
            gap: -45,
            delay: 500,
            duration: 500,
            template: {
              translateX: [-10, 0, "px"],
              opacity: [0, 1]
            }
          });
        }, {
          triggerOnce: true,
          offset: 400
        });
      },
      animateTabs: function() {
        var _this = this;
        return jQuery("#fog-tabs").waypoint(function() {
          return new Animo({
            el: jQuery("#fog-tabs .row > div"),
            duration: 600,
            gap: -5,
            template: {
              rotateY: [90, 0, "deg"],
              opacity: [0.6, 1]
            }
          });
        }, {
          triggerOnce: true,
          offset: 400
        });
      },
      animateAccordions: function() {
        var _this = this;
        return jQuery("#fog-accordions").waypoint(function() {
          return new Animo({
            el: jQuery("#fog-accordions .row > div"),
            duration: 600,
            gap: -5,
            template: {
              rotateX: [90, 0, "deg"],
              opacity: [0.6, 1],
              skewY: [-20, 0, "deg"]
            }
          });
        }, {
          triggerOnce: true,
          offset: 400
        });
      },
      animateWell: function() {
        var _this = this;
        return jQuery("#fog-blockwell").waypoint(function() {
          return new Animo({
            el: jQuery("#fog-blockwell .well"),
            duration: 400,
            delay: 50,
            gap: -5,
            template: {
              opacity: [0, 1],
              translateY: [-20, 0, "px"]
            }
          });
        }, {
          triggerOnce: true,
          offset: 400
        });
      },
      animateDropProgress: function() {
        var _this = this;
        return jQuery("#fog-drop-progress").waypoint(function() {
          return new Animo({
            el: jQuery("#fog-drop-progress .row > div"),
            duration: 400,
            delay: 50,
            gap: -5,
            template: {
              opacity: [0, 1],
              translateY: [-20, 0, "px"]
            }
          });
        }, {
          triggerOnce: true,
          offset: 400
        });
      },
      animateTypeList: function() {
        var _this = this;
        return jQuery("#fog-typelist").waypoint(function() {
          return new Animo({
            el: jQuery("#fog-typelist .row > div"),
            duration: 400,
            delay: 50,
            gap: -60,
            template: {
              opacity: [0, 1],
              translateX: [10, 0, "px"]
            }
          }, {
            el: jQuery("#fog-typelist h4.upper"),
            duration: 600,
            delay: 50,
            template: {
              opacity: [0, 1]
            }
          });
        }, {
          triggerOnce: true,
          offset: 400
        });
      },
      animateAjaxPortfolio: function() {
        var _this = this;
        return jQuery("#fog-ajax-portfolio").waypoint(function() {
          return new Animo({
            el: jQuery("#fog-ajax-portfolio h4.upper"),
            duration: 600,
            delay: 50,
            template: {
              opacity: [0, 1]
            }
          }, {
            el: jQuery("#fog-ajax-portfolio .portfolio-list li"),
            duration: 500,
            delay: 500,
            gap: -85,
            easing: "easeOutBack",
            template: {
              opacity: [0, 1],
              scale: [0, 1],
              rotate: [-90, 0, "deg"]
            }
          });
        }, {
          triggerOnce: true,
          offset: 400
        });
      },
      animateButtons: function() {
        var _this = this;
        return jQuery("#fog-buttons").waypoint(function() {
          return new Animo({
            el: jQuery("#fog-buttons h4.upper"),
            duration: 600,
            delay: 50,
            template: {
              opacity: [0, 1]
            }
          }, {
            el: jQuery("#fog-buttons p"),
            delay: 500,
            duration: 400,
            gap: -50,
            easing: "easeOutBounce",
            template: {
              opacity: [0, 1],
              translateX: [20, 0, "px"]
            }
          });
        }, {
          triggerOnce: true,
          offset: 400
        });
      },
      animateMessages: function() {
        var _this = this;
        return jQuery("#fog-messages").waypoint(function() {
          return new Animo({
            el: jQuery("#fog-messages h4.upper"),
            duration: 600,
            delay: 50,
            template: {
              opacity: [0, 1]
            }
          }, {
            el: jQuery("#fog-messages .alert"),
            duration: 400,
            delay: 500,
            gap: -70,
            template: {
              opacity: [0.6, 1],
              rotateY: [65, 0, "deg"]
            }
          });
        }, {
          triggerOnce: true,
          offset: 400
        });
      },
      animateContentBox: function() {
        var _this = this;
        return jQuery("#fog-contentbox").waypoint(function() {
          return new Animo({
            el: jQuery("#fog-contentbox h4.upper"),
            duration: 600,
            delay: 50,
            template: {
              opacity: [0, 1]
            }
          }, {
            el: jQuery("#fog-contentbox .row > div"),
            duration: 400,
            delay: 500,
            gap: -85,
            easing: "easeOutCirc",
            template: {
              opacity: [0.6, 1],
              translateY: [150, 0, "px"]
            }
          });
        }, {
          triggerOnce: true,
          offset: 400
        });
      },
      animateTestimonials: function() {
        var _this = this;
        return jQuery("#fog-testimonials").waypoint(function() {
          return new Animo({
            el: jQuery("#fog-testimonials h4.upper"),
            duration: 600,
            delay: 50,
            template: {
              opacity: [0, 1]
            }
          }, {
            el: jQuery("#fog-testimonials .row > div"),
            duration: 400,
            delay: 500,
            gap: -55,
            easing: "easeOutCirc",
            template: {
              opacity: [0.6, 1],
              rotateY: [150, 0, "deg"]
            }
          });
        }, {
          triggerOnce: true,
          offset: 400
        });
      },
      animateScForm: function() {
        var _this = this;
        return jQuery("#fog-sc-contact").waypoint(function() {
          return new Animo({
            el: jQuery("#fog-sc-contact h4.upper"),
            duration: 600,
            delay: 50,
            template: {
              opacity: [0, 1]
            }
          }, {
            el: jQuery("#fog-sc-contact form .fog"),
            duration: 400,
            delay: 500,
            gap: -55,
            easing: "easeOutCirc",
            template: {
              opacity: [0, 1]
            }
          });
        }, {
          triggerOnce: true,
          offset: 400
        });
      }
    };

    Fog.prototype.initColorbox = function() {
      jQuery(".gallery-box a").colorbox({
        rel: 'group1',
        maxWidth: "90%",
        maxHeight: "90%"
      });
    };

    Fog.prototype.initIntroduction = function() {
      new Animo({
        el: jQuery("#intro h1"),
        duration: 200,
        template: {
          scale: [2, 1],
          opacity: [0, 1]
        }
      }, {
        el: jQuery("#intro p"),
        duration: 800,
        gap: -65,
        template: {
          opacity: [0, 1]
        }
      });
      this.initApple();
    };

    Fog.prototype.initApple = function() {
      new Animo({
        el: jQuery(".apple-block .iphone"),
        easing: "easeOutBack",
        template: {
          right: [-150, 227, "px"],
          opacity: [0, 1]
        }
      }, {
        el: jQuery(".apple-block .imac"),
        duration: 500,
        delay: 300,
        template: {
          scale: [1.1, 1],
          opacity: [0, 1]
        }
      }, {
        el: jQuery(".apple-block .ipadmini"),
        template: {
          opacity: [0, 1],
          right: [-150, 153, "px"]
        }
      }, {
        el: jQuery(".apple-block .ipad"),
        easing: "easeOutSine",
        duration: 500,
        template: {
          opacity: [0.8, 1],
          right: [0, 257, "px"]
        }
      }, {
        el: jQuery(".apple-block .macbookpro"),
        duration: 500,
        delay: 100,
        template: {
          opacity: [1, 1],
          "rotateY": [45, 0, "deg"]
        }
      }, {
        el: jQuery(".apple-block .apple-assets"),
        duration: 500,
        delay: 100,
        template: {
          opacity: [0, 1]
        }
      });
    };

    Fog.prototype.initMap = function() {
      if (jQuery("#gmap").size() > 0) {
        this.setMap("gmap", 40.728527, -73.995881, "Fog all around");
      }
    };

    Fog.prototype.setMap = function(id, lat, lng, info, zoom) {
      var infowindow, map, mapOptions, marker, myLatlng;
      if (id == null) {
        id = "gmap";
      }
      if (lat == null) {
        lat = -25.363882;
      }
      if (lng == null) {
        lng = 131.044922;
      }
      if (zoom == null) {
        zoom = 12;
      }
      myLatlng = new google.maps.LatLng(lat, lng);
      mapOptions = {
        zoom: zoom,
        center: myLatlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        scrollwheel: false
      };
      map = new google.maps.Map(document.getElementById(id), mapOptions);
      infowindow = new google.maps.InfoWindow({
        content: info
      });
      marker = new google.maps.Marker({
        position: myLatlng,
        map: map,
        title: ''
      });
      google.maps.event.addListener(marker, "click", function() {
        return infowindow.open(map, marker);
      });
    };

    Fog.prototype.initScrollTo = function() {
      return jQuery(".main-menu a").on("click", function() {
        var $this, href, parent;
        $this = jQuery(this);
        parent = $this.parent().siblings();
        href = $this.attr("href");
        parent.find("a").removeClass("current-item");
        $this.addClass("current-item");
        if (/^#/.test(href)) {
          return jQuery.scrollTo(href, 800);
        } else {
          return window.location = href;
        }
      });
    };

    Fog.prototype.quoteSlider = function() {
      return jQuery("#quote-slider1").bxSlider({
        auto: true,
        pause: 7000,
        controls: false
      });
    };

    Fog.prototype.twitterSlider = function() {
      return jQuery(".twitter-slides").bxSlider({
        auto: true,
        controls: false,
        pager: false,
        mode: "vertical"
      });
    };

    Fog.prototype.slideshowSlider = function() {
      jQuery(".slideshow").bxSlider({
        auto: true,
        pause: 7000,
        controls: false
      });
      if (jQuery(".slideshow").parent().parent().parent().hasClass("filter-content")) {
        return jQuery(".slideshow").parent().parent().parent().addClass("hidden");
      }
    };

    Fog.prototype.testimonialsSlider = function() {
      var bxslide;
      bxslide = jQuery(".slider-testimonials .testimonials").bxSlider({
        pause: 7000,
        auto: true,
        controls: false,
        pager: false
      });
      jQuery(".slidesjs-previous").on("click", function() {
        bxslide.goToPrevSlide();
        return false;
      });
      return jQuery(".slidesjs-next").on("click", function() {
        bxslide.goToNextSlide();
        return false;
      });
    };

    Fog.prototype.fogProgress = function() {
      return jQuery(".fog-progress").each(function() {
        var el, progress;
        el = jQuery(this);
        progress = el.data("complete");
        return setTimeout(function() {
          return el.find(".progress-complete").animate({
            width: progress + "%"
          }, 2500);
        }, 2400);
      });
    };

    Fog.prototype.styleCollapse = function() {
      return jQuery(".accordion-toggle").on("click", function() {
        var $this, container, containerPanels, currentPanel, header, prevHeader;
        $this = jQuery(this);
        header = $this.closest(".panel-heading");
        container = $this.closest(".panel-group");
        containerPanels = container.find(".panel");
        currentPanel = $this.closest(".panel");
        $this.toggleClass("is-open");
        $this.find(".collapse-icon").toggleClass("is-open");
        if ($this.hasClass("is-open")) {
          header.addClass("is-open");
          $this.find("i").removeClass("icon-plus").addClass("icon-minus");
        } else {
          header.removeClass("is-open");
          $this.find("i").removeClass("icon-minus").addClass("icon-plus");
        }
        if (container.is("#accordion")) {
          prevHeader = currentPanel.siblings(".panel").find(".panel-heading");
          prevHeader.removeClass("is-open");
          prevHeader.find(".accordion-toggle").removeClass("is-open");
          prevHeader.find(".collapse-icon").removeClass("is-open");
          return prevHeader.find("i").removeClass("icon-minus").addClass("icon-plus");
        }
      });
    };

    Fog.prototype.ajaxBinds = function() {
      var fog;
      fog = this;
      jQuery("#fog-blog-pagination a").on("click", function(e) {
        e.preventDefault();
        return fog.ajaxCall(jQuery(this).attr('href'), function(r) {
          return jQuery('#blog-inner').fadeOut(250).html(r).fadeIn(250);
        });
      });
      jQuery('body').on("click", ".portfolio-single .closex", function(e) {
        e.preventDefault();
        jQuery('#portfolio-single-page').slideUp(250, function(e) {
          return jQuery(this).html('');
        });
        return jQuery.scrollTo('#portfolio', 800, {
          offset: {
            top: -100
          }
        });
      });
      jQuery('body').on("click", '.portfolio-list .ajax a', function(e) {
        e.preventDefault();
        return fog.ajaxCall(jQuery(this).attr('href'), function(r) {
          jQuery('#portfolio-single-page').fadeOut(250).html(r).fadeIn(250);
          fog.slideshowSlider();
          return jQuery.scrollTo('.portfolio-single', 800, {
            offset: {
              top: -100
            }
          });
        });
      });
      jQuery("body").on("click", "#blog-inner .fog-title a, #blog-inner a.read-more", function(e) {
        e.preventDefault();
        return fog.ajaxCall(jQuery(this).attr('href'), function(r) {
          jQuery('#blog-single').fadeOut(250).html(r).fadeIn(250);
          return jQuery.scrollTo("#blog-single", 800);
        });
      });
      jQuery("body").on("submit", "#write-comment", function(e) {
        var form, req;
        e.preventDefault();
        fog.loading(true);
        form = jQuery(this);
        req = jQuery.post("ajax/save-comment.php", form.serializeArray(), function(r) {
          var html;
          fog.loading(false);
          r = jQuery.parseJSON(r);
          jQuery('#comments-f\
\
\
					orm-submitted').remove();
          if (r.error === false) {
            html = "<div id='comments-form-submitted' class='alert alert-success'>" + r.message + "</div>";
            return form.next().next().after(html);
          } else {
            html = "<div id='comments-form-submitted' class='alert alert-warning'>" + r.message + "</div>";
            return form.next().next().after(html);
          }
        });
        return req.fail(function(w) {
          return fog.loading(false);
        });
      });
      return jQuery('.fog-contact-form').on("submit", function(e) {
        var form, req;
        fog.loading(true);
        form = jQuery(this);
        req = jQuery.post("ajax/send-contact-form.php", form.serializeArray(), function(r) {
          var html;
          fog.loading(false);
          r = jQuery.parseJSON(r);
          jQuery('#contact-form-submitted').remove();
          if (r.error === false) {
            html = "<div id='contact-form-submitted'><div class='clearfix'>&nbsp;</div><div class='clearfix'>&nbsp;</div> <div class='alert alert-success'>" + r.message + "</div></div>";
            return form.after(html);
          } else {
            html = "<div id='contact-form-submitted'><div class='clearfix'>&nbsp;</div><div class='clearfix'>&nbsp;</div> <div class='alert alert-warning'>" + r.message + "</div></div>";
            return form.after(html);
          }
        });
        return e.preventDefault();
      });
    };

    Fog.prototype.ajaxCall = function(w, cb) {
      var req,
        _this = this;
      this.loading(true);
      req = jQuery.get(w, function(r) {
        cb(r);
        _this.loading(false);
        return _this.initColorbox();
      });
      req.fail(function(w) {
        alert('Sorry, request failed !');
        return _this.loading(false);
      });
      return "";
    };

    Fog.prototype.loading = function(w) {
      var l;
      if (w == null) {
        w = true;
      }
      l = jQuery('#spinner');
      if (w === true) {
        return l.fadeIn();
      } else {
        return l.fadeOut();
      }
    };

    return Fog;

  })();

  Responsive = {
    init: function() {
      var width;
      this.rMenu();
      return width = jQuery("body").width();
    },
    rMenu: function() {
      var width;
      return width = jQuery("body").width();
    }
  };

  jQuery(function() {
    Fog = new Fog;
    jQuery(window).on("FOG_DOM_READY", function(e) {
      return Fog.initRevolutionSlider();
    });
    Responsive.init();
    return jQuery(window).on("resize", function() {
      return Responsive.init();
    });
  });

}).call(this);
